name = "blogtemplate"
compatibility_date = "2025-01-01"

main = "dist/_worker.js/index.js"

[assets]
binding = "ASSETS"
directory = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "blogdatabase"
database_id = "c32058e0-7666-4284-8130-c8cceb090a82"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "blogimage"

[observability]
enabled = true
